osx_image: xcode10.1
language: objective-c
cache: cocoapods
install:
- pod install --project-directory=mi-ios-2019 || pod install --project-directory=mi-ios-2019 --repo-update
script:
- set -o pipefail && xcodebuild test -scheme mi-ios-2019 -workspace mi-ios-2019/mi-ios-2019.xcworkspace -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.1' | xcpretty