osx_image: xcode10.1
language: objective-c
cache: cocoapods
install:
- gem update bundler
- bundle install --gemfile mi-ios-2019/Gemfile
- cd mi-ios-2019
- bundle exec pod install || bundle exec pod install --repo-update
- cd -
script:
- set -o pipefail && xcodebuild test -scheme mi-ios-2019 -workspace mi-ios-2019/mi-ios-2019.xcworkspace -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.1' | xcpretty