# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mi-ios-2019' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mi-ios-2019
  pod 'ACKLocalization', '~> 0.1'
  pod 'SwiftGen', '~> 6.0'

end
