# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

target 'mi-ios-2019' do
  # Pods for mi-ios-2019
  pod 'ACKLocalization', '~> 0.1'
  pod 'SwiftGen', '~> 6.0'
  pod 'ReactiveSwift', '~> 4.0'
  pod 'ACKReactiveExtensions', '~> 4.0'
  pod 'SnapKit', '~> 4.2'
end

target 'iMessageApp' do
  pod 'SnapKit', '~> 4.2'
  pod 'ReactiveSwift', '~> 4.0'
end

target 'mi-ios-2019-Unit-Tests' do
  pod 'ReactiveSwift', '~> 4.0'
end

target 'mi-ios-2019-UITests' do
  pod 'ReactiveSwift', '~> 4.0'
end
